version: '3.8'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: notes_db
    volumes:
      - ./postgres:/var/lib/postgresql/data

  app:
    build: .
    container_name: notes_be
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXIRATION_TIME=${JWT_EXIRATION_TIME}
    depends_on:
      - db