services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    container_name: notes_db
    volumes:
      - ./postgres:/var/lib/postgresql/data

  app:
    build: .
    container_name: notes_be
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - db
